# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'LottieTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottieTest
  pod 'lottie-ios', '~> 2.5.3'
  pod 'Masonry'
  # pod 'LookinServer', :configurations => ['Debug', 'Release']

  target 'LottieTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieTestUITests' do
    # Pods for testing
  end
end
